version: "3"

services:
  postgres:
    image: postgres:15-alpine3.18

    container_name: db-postgres
    restart: unless-stopped
    init: true

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./.initdb:/docker-entrypoint-initdb.d
    env_file:
      - ./config/.env
    ports:
      - 5436:5432
  
  pgadmin:
    image: dpage/pgadmin4

    container_name: pg-admin
    restart: unless-stopped
    init: true

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - ./config/.env
    ports:
      - 5050:5050
    depends_on:
      - postgres

  user-segmentation:
    build:
      context: .
      target: final

    container_name: user-segmentation
    restart: unless-stopped
    init: true

    env_file:
      - ./config/.env
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - pgadmin

volumes:
  db-data:
  pgadmin-data: