name: User Segmentation App with Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ vars.RUN_OS }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Set up Go
        run: go version

      - name: Building app
        run: make build

  test:
    name: Test
    needs: build
    runs-on: ${{ vars.RUN_OS }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Running unit tests
        run: make test

  lint:
    name: Lint
    needs: build
    runs-on: ${{ vars.RUN_OS }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52

      - name: Running golangci linters
        run: make lint